#generated by moai-android/cmakelists.txt

include $(CLEAR_VARS)

LOCAL_MODULE := moai-android-adcolony
LOCAL_SRC_FILES := $(MOAI_LIBS)/libmoai-android-adcolony.a
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)

LOCAL_MODULE := moai-android-chartboost
LOCAL_SRC_FILES := $(MOAI_LIBS)/libmoai-android-chartboost.a
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)

LOCAL_MODULE := moai-android-crittercism
LOCAL_SRC_FILES := $(MOAI_LIBS)/libmoai-android-crittercism.a
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)

LOCAL_MODULE := moai-android-facebook
LOCAL_SRC_FILES := $(MOAI_LIBS)/libmoai-android-facebook.a
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)

LOCAL_MODULE := moai-android-flurry
LOCAL_SRC_FILES := $(MOAI_LIBS)/libmoai-android-flurry.a
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)

LOCAL_MODULE := moai-android-flurry-ads
LOCAL_SRC_FILES := $(MOAI_LIBS)/libmoai-android-flurry-ads.a
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)

LOCAL_MODULE := moai-android-google-analytics
LOCAL_SRC_FILES := $(MOAI_LIBS)/libmoai-android-google-analytics.a
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)

LOCAL_MODULE := moai-android-google-play-services
LOCAL_SRC_FILES := $(MOAI_LIBS)/libmoai-android-google-play-services.a
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)

LOCAL_MODULE := moai-android-google-play-services-games
LOCAL_SRC_FILES := $(MOAI_LIBS)/libmoai-android-google-play-services-games.a
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)

LOCAL_MODULE := moai-android-tapjoy
LOCAL_SRC_FILES := $(MOAI_LIBS)/libmoai-android-tapjoy.a
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)

LOCAL_MODULE := moai-android-twitter
LOCAL_SRC_FILES := $(MOAI_LIBS)/libmoai-android-twitter.a
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)

LOCAL_MODULE := moai-android-vungle
LOCAL_SRC_FILES := $(MOAI_LIBS)/libmoai-android-vungle.a
include $(PREBUILT_STATIC_LIBRARY)

