# Generated by CMake 3.0.2

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget cpufeatures box2d contrib crypto curl cares expat freetype jansson jpg liblua-static luafilesystem luasql luacurl luacrypto luasocket mongoose ogg png sfmt sqlite3 spine ssl tess tinyxml tlsf vorbis webp zlib untz zlvfs zlcrypto zlcore moai-core moai-util moai-sim moai-crypto moai-box2d moai-untz moai-fmod-studio moai-http-client moai-luaext moai-audiosampler moai-spine moai-android-adcolony moai-android-chartboost moai-android-crittercism moai-android-facebook moai-android-flurry moai-android-flurry-ads moai-android-google-analytics moai-android-google-play-services moai-android-google-play-services-games moai-android-tapjoy moai-android-twitter moai-android-vungle moai-android)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)

# Create imported target cpufeatures
add_library(cpufeatures STATIC IMPORTED)

set_target_properties(cpufeatures PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/cpufeatures"
)

# Create imported target box2d
add_library(box2d STATIC IMPORTED)

# Create imported target contrib
add_library(contrib STATIC IMPORTED)

set_target_properties(contrib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/contrib"
)

# Create imported target crypto
add_library(crypto STATIC IMPORTED)

# Create imported target curl
add_library(curl STATIC IMPORTED)

# Create imported target cares
add_library(cares STATIC IMPORTED)

# Create imported target expat
add_library(expat STATIC IMPORTED)

set_target_properties(expat PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "XML_STATIC"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/expat"
)

# Create imported target freetype
add_library(freetype STATIC IMPORTED)

# Create imported target jansson
add_library(jansson STATIC IMPORTED)

# Create imported target jpg
add_library(jpg STATIC IMPORTED)

# Create imported target liblua-static
add_library(liblua-static STATIC IMPORTED)

# Create imported target luafilesystem
add_library(luafilesystem STATIC IMPORTED)

# Create imported target luasql
add_library(luasql STATIC IMPORTED)

# Create imported target luacurl
add_library(luacurl STATIC IMPORTED)

# Create imported target luacrypto
add_library(luacrypto STATIC IMPORTED)

# Create imported target luasocket
add_library(luasocket STATIC IMPORTED)

# Create imported target mongoose
add_library(mongoose STATIC IMPORTED)

# Create imported target ogg
add_library(ogg STATIC IMPORTED)

# Create imported target png
add_library(png STATIC IMPORTED)

set_target_properties(png PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PNG_SKIP_SETJMP_CHECK=1"
)

# Create imported target sfmt
add_library(sfmt STATIC IMPORTED)

# Create imported target sqlite3
add_library(sqlite3 STATIC IMPORTED)

# Create imported target spine
add_library(spine STATIC IMPORTED)

# Create imported target ssl
add_library(ssl STATIC IMPORTED)

# Create imported target tess
add_library(tess STATIC IMPORTED)

# Create imported target tinyxml
add_library(tinyxml STATIC IMPORTED)

set_target_properties(tinyxml PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/tinyxml"
)

# Create imported target tlsf
add_library(tlsf STATIC IMPORTED)

# Create imported target vorbis
add_library(vorbis STATIC IMPORTED)

# Create imported target webp
add_library(webp STATIC IMPORTED)

set_target_properties(webp PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/webp"
)

# Create imported target zlib
add_library(zlib STATIC IMPORTED)

# Create imported target untz
add_library(untz STATIC IMPORTED)

# Create imported target zlvfs
add_library(zlvfs STATIC IMPORTED)

# Create imported target zlcrypto
add_library(zlcrypto STATIC IMPORTED)

# Create imported target zlcore
add_library(zlcore STATIC IMPORTED)

set_target_properties(zlcore PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/expat"
)

# Create imported target moai-core
add_library(moai-core STATIC IMPORTED)

set_target_properties(moai-core PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include/lua"
)

# Create imported target moai-util
add_library(moai-util STATIC IMPORTED)

set_target_properties(moai-util PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/moai-util;${_IMPORT_PREFIX}/include/expat;${_IMPORT_PREFIX}/include/tinyxml"
)

# Create imported target moai-sim
add_library(moai-sim STATIC IMPORTED)

set_target_properties(moai-sim PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include/freetype"
)

# Create imported target moai-crypto
add_library(moai-crypto STATIC IMPORTED)

set_target_properties(moai-crypto PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target moai-box2d
add_library(moai-box2d STATIC IMPORTED)

set_target_properties(moai-box2d PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target moai-untz
add_library(moai-untz STATIC IMPORTED)

set_target_properties(moai-untz PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include/untz"
)

# Create imported target moai-fmod-studio
add_library(moai-fmod-studio STATIC IMPORTED)

set_target_properties(moai-fmod-studio PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include/fmod-studio"
)

# Create imported target moai-http-client
add_library(moai-http-client STATIC IMPORTED)

set_target_properties(moai-http-client PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/moai-http-client"
)

# Create imported target moai-luaext
add_library(moai-luaext STATIC IMPORTED)

set_target_properties(moai-luaext PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/moai-luaext"
)

# Create imported target moai-audiosampler
add_library(moai-audiosampler STATIC IMPORTED)

set_target_properties(moai-audiosampler PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target moai-spine
add_library(moai-spine STATIC IMPORTED)

set_target_properties(moai-spine PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target moai-android-adcolony
add_library(moai-android-adcolony STATIC IMPORTED)

# Create imported target moai-android-chartboost
add_library(moai-android-chartboost STATIC IMPORTED)

# Create imported target moai-android-crittercism
add_library(moai-android-crittercism STATIC IMPORTED)

# Create imported target moai-android-facebook
add_library(moai-android-facebook STATIC IMPORTED)

# Create imported target moai-android-flurry
add_library(moai-android-flurry STATIC IMPORTED)

# Create imported target moai-android-flurry-ads
add_library(moai-android-flurry-ads STATIC IMPORTED)

# Create imported target moai-android-google-analytics
add_library(moai-android-google-analytics STATIC IMPORTED)

# Create imported target moai-android-google-play-services
add_library(moai-android-google-play-services STATIC IMPORTED)

# Create imported target moai-android-google-play-services-games
add_library(moai-android-google-play-services-games STATIC IMPORTED)

# Create imported target moai-android-tapjoy
add_library(moai-android-tapjoy STATIC IMPORTED)

# Create imported target moai-android-twitter
add_library(moai-android-twitter STATIC IMPORTED)

# Create imported target moai-android-vungle
add_library(moai-android-vungle STATIC IMPORTED)

# Create imported target moai-android
add_library(moai-android STATIC IMPORTED)

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/libmoai-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
